### ISSUE TITLE
Minimum viable README

### ISSUE THREAD

**Issue by mike-north** [SparshithNR/doc-tester#20]
- [x] #6 document public API in README
- [x] #8 document how inline imports work
- [x] #19 document comment assertion language
